### ISSUE TITLE
proteinPrepare writes N as element for hydrogens

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#101]
I'm looking into it, but have you noticed it @tonigi?

**Comment by j3mdamas** [comment]
If you could do this, I'd really appreciate @tonigi

**Comment by tonigi** [comment]
Should be fixed in 28384f99327dd17c202c5b2c789e103f8e2aba49

**Comment by j3mdamas** [comment]
I can't see that tag and I don't see any new in your activity

**Comment by j3mdamas** [comment]
This is still not fixed. I still get `N` as the element for hydrogen

**Comment by tonigi** [comment]
test case please

**Comment by j3mdamas** [comment]
I just reproduce it on a very specific case. Let me check it out

**Comment by j3mdamas** [comment]
nevermind, forgot to reload module
